name: build

on:
  schedule:
    - cron: '0 2 * * *' # everyday at 2am
  push:

jobs:

  cli:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER  }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Set up for CLI Build
        run: |
          mv docker-php-entrypoint-cli docker-php-entrypoint
          mv Dockerfile-cli Dockerfile
          docker buildx create --name multibuilder
          docker buildx use multibuilder

      - name: Build and Push
        run: |
          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag registry.gitlab.com/grahamcampbell/php8:cli .

  fpm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER  }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Set up for CLI Build
        run: |
          mv docker-php-entrypoint-fpm docker-php-entrypoint
          mv Dockerfile-fpm Dockerfile
          docker buildx create --name multibuilder
          docker buildx use multibuilder

      - name: Build and Push
        run: |
          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag registry.gitlab.com/grahamcampbell/php8:fpm .
