name: build

on:
  schedule:
    - cron: '0 2 * * *' # everyday at 2am
  push:

jobs:

  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to Package Registry
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Set up for CLI Build
        run: |
          mv docker-php-entrypoint-cli docker-php-entrypoint
          mv Dockerfile-cli Dockerfile

      - name: Build and Push
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 180
          max_attempts: 2
          command: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag registry.gitlab.com/grahamcampbell/php8:cli .

  fpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to Package Registry
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Set up for FPM Build
        run: |
          mv docker-php-entrypoint-fpm docker-php-entrypoint
          mv Dockerfile-fpm Dockerfile

      - name: Build and Push
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 180
          max_attempts: 2
          command: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag registry.gitlab.com/grahamcampbell/php8:fpm .
