name: cli

on:
  schedule:
    - cron: '0 2 * * *' # everyday at 2am
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to Package Registry
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up for CLI Build
        run: |
          mv docker-php-entrypoint-cli docker-php-entrypoint
          mv Dockerfile-cli Dockerfile

      - name: Build and Push
        run: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag docker.pkg.github.com/grahamcampbell/php8:cli .

name: fpm

on:
  schedule:
    - cron: '0 2 * * *' # everyday at 2am
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to Package Registry
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up for CLI Build
        run: |
          mv docker-php-entrypoint-fpm docker-php-entrypoint
          mv Dockerfile-fpm Dockerfile

      - name: Build and Push
        run: docker buildx build --push --platform linux/arm64/v8,linux/amd64 --no-cache --tag docker.pkg.github.com/grahamcampbell/php8:fpm .
